name: Bandit Security Scan

on:
  push:
  pull_request:

jobs:
  security:
    name: Run Bandit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Bandit Security Scan
        uses: shundor/bandit-action@v1
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
