name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for Super-Linter to detect changes

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
